### ISSUE TITLE
Size mismatch

### ISSUE THREAD

**Issue by koper89** [xbianonpi/xbian-package-config-xbmc#27]
I got an error trying to upgrade xbian packages:
Failed to fetch mirror://apt.xbian.org/mirror.txt/pool/stable/main/x/xbian-package-config-xbmc/xbian-package-config-xbmc_1.2.0_armhf.deb  Size mismatch
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by mk01** [comment]
this can happen when mirrors are not 100% synced. but error should disappear automatically ... 

is all ok now ?

**Comment by koper89** [comment]
yep - problem solved, sorry for not closing it faster

**Comment by CurlyMoo** [comment]
Should also be solved with the new apt updates that automatically removes mirrors when they are not in sync and adds them again when they are.
