### ISSUE TITLE
TypeError: '<' not supported between instances of 'str' and 'datetime.datetime'

### ISSUE THREAD

**Issue by rafhtl** [xbianonpi/xbian-package-config-xbmc#30]
if self.forceRefresh or ((force or not xbmc.Player().isPlaying()) and self.selfCheck and (getSetting('lastupdatecheck') ==                                                                  None or getSetting('lastupdatecheck') < (self.eventTime - timedelta(days=self.deltaCheck)))):

/usr/local/share/kodi/addons/plugin.xbianconfig/services/xbianworker.py

Kodi 19 (python 3)

Manfred you could use 
startdate = datetime.datetime.strptime('2017-07-07', "%Y-%m-%d").date()
enddate = datetime.datetime.strptime('2017-07-10', "%Y-%m-%d").date()

Thankyou
Raf

**Comment by mkreisl** [comment]
Fixed with this commit: https://github.com/xbianonpi/xbian-package-config-xbmc/commit/f04808c630e24aedcbda02d40e154ef310977d4d
