### ISSUE TITLE
xbianconfig's services.py cannot be stopped properly

### ISSUE THREAD

**Issue by stsichler** [xbianonpi/xbian-package-config-xbmc#33]
Whenever I stop kodi, I see the following entry in the log:

`ERROR <general>: CPythonInvoker(4, /usr/local/share/kodi/addons/plugin.xbianconfig/services.py): script didn't stop in 5 seconds - let's kill it`
`INFO <general>: CPythonInvoker(4, /usr/local/share/kodi/addons/plugin.xbianconfig/services.py): script aborted`

This delays shutting down kodi by 5 seconds.
Any idea what's causing this?

**Comment by mkreisl** [comment]
> Any idea what's causing this?

Not until today. I have just investigated and found that the previously used call-back function has unfortunately been removed without replacement in Kodi v19. Now, unfortunately, you have to poll again for that event, but what a nonsense!
Thanks for the hint

Fix is now WIP

**Comment by stsichler** [comment]
> call-back function has unfortunately been removed without replacement in Kodi v19. Now, unfortunately, you have to poll again for that event, but what a nonsense! 

I agree. That seems a very questionable design decision. 
I'm glad that you found that so fast. Thank you!
